import { RoomOptions, PackOption } from './types/index';

export const ROOM_OPTIONS: RoomOptions = {
  salon: [
    {
      id: 'salon-1',
      name: 'Salon 1',
      description: 'Salon avec mobilier de base',
      image: '/images/salons/s1.webp',
      price: 0,
    },
    {
      id: 'salon-2',
      name: 'Salon 2',
      description: 'Salon avec canapé et fauteuils',
      image: '/images/salons/s2.webp',
      price: 0,
    },
    {
      id: 'salon-3',
      name: 'Salon 3',
      description: 'Salon confortable et fonctionnel',
      image: '/images/salons/s4.webp',
      price: 0,
    },
    {
      id: 'salon-4',
      name: 'Salon 4',
      description: 'Salon avec équipement standard',
      image: '/images/salons/s5.webp',
      price: 0,
    },
    {
      id: 'salon-5',
      name: 'Salon 5',
      description: 'Salon supplémentaire standard',
      image: '/images/salons/s6.webp',
      price: 0,
    },
    {
      id: 'salon-6',
      name: 'Salon 6',
      description: 'Salon supplémentaire standard',
      image: '/images/salons/s7.webp',
      price: 0,
    },
    {
      id: 'salon-7',
      name: 'Salon 7',
      description: 'Salon supplémentaire standard',
      image: '/images/salons/s8.webp',
      price: 0,
      available: false,
    },
    {
      id: 'salon-8',
      name: 'Salon 8',
      description: 'Salon supplémentaire standard',
      image: '/images/salons/s9.webp',
      price: 0,
    },
    {
      id: 'salon-9',
      name: 'Salon 9',
      description: 'Salon supplémentaire standard',
      image: '/images/salons/s10.webp',
      price: 0,
    },
    {
      id: 'salon-10',
      name: 'Salon 10',
      description: 'Salon supplémentaire standard',
      image: '/images/salons/s11.webp',
      price: 0,
      available: false,
    },
    {
      id: 'salon-11',
      name: 'Salon 11',
      description: 'Salon supplémentaire standard',
      image: '/images/salons/s12.webp',
      price: 0,
    },
    {
      id: 'salon-12',
      name: 'Salon 12',
      description: 'Salon supplémentaire standard',
      image: '/images/salons/s13.webp',
      price: 0,
    },
    {
      id: 'salon-13',
      name: 'Salon 13',
      description: 'Salon supplémentaire standard',
      image: '/images/salons/s14.webp',
      price: 0,
      available: false,
    },
    {
      id: 'salon-14',
      name: 'Salon 14',
      description: 'Salon supplémentaire standard',
      image: '/images/salons/s15.webp',
      price: 0,
    },
    {
      id: 'salon-15',
      name: 'Salon 15',
      description: 'Salon supplémentaire standard',
      image: '/images/salons/s16.webp',
      price: 0,
    },
  ],
  'salle-a-manger': [
    {
      id: 'sam-1',
      name: 'Salle à Manger 1',
      description: 'Espace repas avec table',
      image: '/images/salle-a-manger/sam1.webp',
      price: 0,
    },
    {
      id: 'sam-2',
      name: 'Salle à Manger 2',
      description: 'Salle à manger avec mobilier de base',
      image: '/images/salle-a-manger/sam2.webp',
      price: 0,
    },
    {
      id: 'sam-3',
      name: 'Salle à Manger 3',
      description: 'Espace repas standard',
      image: '/images/salle-a-manger/sam3.webp',
      price: 0,
    },
    {
      id: 'sam-4',
      name: 'Salle à Manger 4',
      description: 'Salle à manger avec ensemble table',
      image: '/images/salle-a-manger/sam4.webp',
      price: 0,
      available: false,
    },
    {
      id: 'sam-5',
      name: 'Salle à Manger 5',
      description: 'Espace repas fonctionnel',
      image: '/images/salle-a-manger/sam5.webp',
      price: 0,
    },
  ],
  chambre: [
    {
      id: 'chambre-1',
      name: 'Chambre 1',
      description: 'Chambre avec lit et rangements',
      image: '/images/chambres/c1.webp',
      price: 0,
    },
    {
      id: 'chambre-2',
      name: 'Chambre 2',
      description: 'Chambre standard avec mobilier de base',
      image: '/images/chambres/chambre2.webp',
      price: 0,
      //available: false,
    },
    {
      id: 'chambre-3',
      name: 'Chambre 3',
      description: 'Chambre avec espace de couchage et rangement',
      image: '/images/chambres/chambre3.webp',
      price: 0,
      available: false,
    },
    {
      id: 'chambre-4',
      name: 'Chambre 4',
      description: 'Chambre fonctionnelle et pratique',
      image: '/images/chambres/chambre4.webp',
      price: 0,
      available: false,
    },
    {
      id: 'chambre-5',
      name: 'Chambre 5',
      description: 'Chambre confortable et moderne',
      image: '/images/chambres/chambre5.webp',
      price: 0,
    },
  ]
};
